# Assignment | TensorFlow Fundamentals

## Part-1 Theoritical Question

1. What are the different data structures used in Tensorflow?. Give some examples

2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example

3. Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.

Ans.

In TensorFlow, there are several data structures used to represent and manipulate data. The most commonly used data structures in TensorFlow are:

Tensor: A tensor is a fundamental data structure in TensorFlow. It represents a multi-dimensional array of elements of the same data type. Tensors can have any number of dimensions, and they are the primary way to store and manipulate data in TensorFlow.

Variable: A variable is a special type of tensor that is mutable and can be updated during the execution of a TensorFlow graph. Variables are typically used to store model parameters that need to be learned and updated through optimization algorithms like gradient descent.

Placeholder: A placeholder is a way to feed external data into a TensorFlow graph. It is used when you want to define a computation graph but don't have the actual data at the time of graph construction. Placeholders are typically used for inputs or targets during model training.

SparseTensor: A SparseTensor is a special data structure used to represent sparse data, where most of the elements are zeros. It efficiently stores only the non-zero elements and their indices, saving memory and computation.

In the example above, a TensorFlow constant constant is created with a value of 5, and a TensorFlow variable variable is created with an initial value of 2. The variable can be updated and changed during the execution of the TensorFlow graph, while the constant's value remains fixed throughout the execution.

Now, let's describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow:

- Matrix Addition:

To perform matrix addition in TensorFlow, you can use the tf.add() function. The matrices must have the same shape for element-wise addition.

- Matrix Multiplication:
    
To perform matrix multiplication in TensorFlow, you can use the tf.matmul() function or the @ operator. The matrices' dimensions must be compatible for multiplication (e.g., the number of columns in the first matrix must match the number of rows in the second matrix).

- Element-wise Operations:

Element-wise operations in TensorFlow are performed by applying arithmetic operations directly to tensors with the same shape. TensorFlow provides various element-wise operations, including addition (tf.add()), subtraction (tf.subtract()), multiplication (tf.multiply()), division (tf.divide()), and more.

## Part-2: Practical Implementation:
## Task-1 Creating and Manipulating Matrix

1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.

2. Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display the values of matrix B.

3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values of matrix C.

4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [2]:
pip install tensorflow


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 MB 2.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 42.1 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 21.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 60.0 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 12.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 47.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 73.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 55.2 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 57.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 11.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━

In [3]:
import tensorflow as tf

# Create matrix A with dimensions 2x2
A = tf.random.normal(shape=(2, 2))

# Display values of matrix A
print("Matrix A:")
print(A.numpy())

# Create Gaussian matrix B with dimensions x
x = 2  # Define the desired size of matrix B
B = tf.random.truncated_normal(shape=(x, x))

# Display values of matrix B
print("\nMatrix B:")
print(B.numpy())

# Create matrix C with dimensions 2x2 using normal distribution
mean = 2
stddev = 0.5  # Choose your desired standard deviation
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)

# Display values of matrix C
print("\nMatrix C:")
print(C.numpy())

# Perform matrix addition between A and B
D = tf.add(A, B)

# Perform matrix multiplication between C and D
E = tf.matmul(C, D)

# Display values of matrix E
print("\nMatrix E:")
print(E.numpy())


2023-06-13 10:19:17.800268: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-13 10:19:17.867148: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-13 10:19:17.868336: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-13 10:19:18.971475: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


Matrix A:
[[-0.22148782  1.1334692 ]
 [-1.8594246   0.14903094]]

Matrix B:
[[ 0.7880862   0.11220184]
 [-0.09266343  1.403339  ]]

Matrix C:
[[1.9059192 2.148789 ]
 [1.3556771 2.5974288]]

Matrix E:
[[-3.1147342  5.7098637]
 [-4.302285   5.720898 ]]


## Task-2: Performing Additional Matrix Operation:

1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.

2. Calculate the transpose of matrix F and store the result in matrix G

3. Calculate the elementDwise exponential of matrix F and store the result in matrix H.

4. Create a matrix I by concatenating matrix F and matrix G horizontally.

5. Create a matrix J by concatenating matrix F and matrix H vertically



In [4]:
import tensorflow as tf

# Create matrix F with dimensions 2x2 initialized with random values
F = tf.random.uniform(shape=(2, 2))

# Display values of matrix F
print("Matrix F:")
print(F.numpy())

# Calculate the transpose of matrix F and store the result in matrix G
G = tf.transpose(F)

# Display values of matrix G
print("\nMatrix G (Transpose of F):")
print(G.numpy())

# Calculate the elementwise exponential of matrix F and store the result in matrix H
H = tf.exp(F)

# Display values of matrix H
print("\nMatrix H (Elementwise Exponential of F):")
print(H.numpy())

# Create matrix I by concatenating matrix F and matrix G horizontally
I = tf.concat([F, G], axis=1)

# Display values of matrix I
print("\nMatrix I (Concatenation of F and G horizontally):")
print(I.numpy())

# Create matrix J by concatenating matrix F and matrix H vertically
J = tf.concat([F, H], axis=0)

# Display values of matrix J
print("\nMatrix J (Concatenation of F and H vertically):")
print(J.numpy())


Matrix F:
[[0.17933619 0.8513458 ]
 [0.23404443 0.5326884 ]]

Matrix G (Transpose of F):
[[0.17933619 0.23404443]
 [0.8513458  0.5326884 ]]

Matrix H (Elementwise Exponential of F):
[[1.1964229 2.3427975]
 [1.2637006 1.7035059]]

Matrix I (Concatenation of F and G horizontally):
[[0.17933619 0.8513458  0.17933619 0.23404443]
 [0.23404443 0.5326884  0.8513458  0.5326884 ]]

Matrix J (Concatenation of F and H vertically):
[[0.17933619 0.8513458 ]
 [0.23404443 0.5326884 ]
 [1.1964229  2.3427975 ]
 [1.2637006  1.7035059 ]]
